// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBeRdSVOq3Ce8dVLoVAQHjMAOwHE_r3xI',
    appId: '1:453994042479:web:4d4695d4cc693522c1a99a',
    messagingSenderId: '453994042479',
    projectId: 'emart-7e93b',
    authDomain: 'emart-7e93b.firebaseapp.com',
    storageBucket: 'emart-7e93b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6dZdDqPFlink4ar-fErtPNFo1vrjQOhU',
    appId: '1:453994042479:android:9f9374f11fb8594bc1a99a',
    messagingSenderId: '453994042479',
    projectId: 'emart-7e93b',
    storageBucket: 'emart-7e93b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvlCrmYiEv03aqA_rG4Mnw32QNPhqNsHk',
    appId: '1:453994042479:ios:f7e3c0a4e88a9a99c1a99a',
    messagingSenderId: '453994042479',
    projectId: 'emart-7e93b',
    storageBucket: 'emart-7e93b.appspot.com',
    iosClientId: '453994042479-tgb48764gecrb96dnsvb6p9c2eqvu3mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvlCrmYiEv03aqA_rG4Mnw32QNPhqNsHk',
    appId: '1:453994042479:ios:f7e3c0a4e88a9a99c1a99a',
    messagingSenderId: '453994042479',
    projectId: 'emart-7e93b',
    storageBucket: 'emart-7e93b.appspot.com',
    iosClientId: '453994042479-tgb48764gecrb96dnsvb6p9c2eqvu3mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );
}
